parser: '@typescript-eslint/parser'

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-object-literal-type-assertion': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-parameter-properties': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-unused-vars':
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: true
  'react/display-name': off
  'react/prop-types': off

settings:
  react:
    version: detect
